# Generated by Django 4.1.13 on 2024-02-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_ke_num_alter_customuser_num_people'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
