# Generated by Django 4.1.13 on 2024-02-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bill_month_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='appliance_id',
            new_name='appliance',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='room_id',
            new_name='room',
        ),
    ]
