# Generated by Django 4.1.13 on 2024-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cost_alter_room_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAdjustment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')])),
                ('adj_factor', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.AlterField(
            model_name='appliance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
