# Generated by Django 4.1.13 on 2024-03-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_monthlyadjustment_adj_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='wattage',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='sub_category',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
    ]
