# Generated by Django 4.1.13 on 2024-03-01 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_populate_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='year',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='predict_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
