# Generated by Django 5.0.2 on 2024-04-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tip_tipcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipcategory',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
